### ISSUE TITLE
memory overlap

### ISSUE THREAD

**Issue by mattfidler** [nlmixr2/nlmixr2est#124]
```sh
=================================================================
==40434==ERROR: AddressSanitizer: memcpy-param-overlap: memory ranges [0x61e0002353c8,0x61e000235490) and [0x61e000235320, 0x61e0002353e8) overlap
    #0 0x7f22165461ed in __interceptor_memcpy ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:827
    #1 0x7f21eebf182b in void arma::arrayops::copy<double>(double*, double const*, unsigned int) /usr/local/RDsan/lib/R/site-library/RcppArmadillo/include/armadillo_bits/arrayops_meat.hpp:39
    #2 0x7f21eebf182b in arma::Mat<double>::operator=(arma::Mat<double> const&) /usr/local/RDsan/lib/R/site-library/RcppArmadillo/include/armadillo_bits/Mat_meat.hpp:923
    #3 0x7f21eec35c3c in bool arma::op_chol::apply_direct<arma::Mat<double> >(arma::Mat<arma::Mat<double>::elem_type>&, arma::Base<arma::Mat<double>::elem_type, arma::Mat<double> > const&, unsigned int) /usr/local/RDsan/lib/R/site-library/RcppArmadillo/include/armadillo_bits/op_chol_meat.hpp:51
    #4 0x7f21eebfab0d in arma::enable_if2<arma::is_supported_blas_type<arma::Mat<double>::elem_type>::value, bool>::result arma::chol<arma::Mat<double> >(arma::Mat<arma::Mat<double>::elem_type>&, arma::Base<arma::Mat<double>::elem_type, arma::Mat<double> > const&, char const*) (/tmp/RtmptslIwA/nlmixr2est.Rcheck/nlmixr2est/libs/nlmixr2est.so+0x13a1b0d)
    #5 0x7f21eea7f4b1 in LikInner2(double*, int, int) /tmp/RtmptslIwA/nlmixr2est.Rcheck/00_pkg_src/nlmixr2est/src/inner.cpp:1273
    #6 0x7f21eea8e902 in innerOpt1 /tmp/RtmptslIwA/nlmixr2est.Rcheck/00_pkg_src/nlmixr2est/src/inner.cpp:1639
    #7 0x7f21eea9a41f in innerOptId /tmp/RtmptslIwA/nlmixr2est.Rcheck/00_pkg_src/nlmixr2est/src/inner.cpp:1900
    #8 0x7f21eea9b730 in innerOpt() /tmp/RtmptslIwA/nlmixr2est.Rcheck/00_pkg_src/nlmixr2est/src/inner.cpp:1950
    #9 0x7f21eea9c4be in foceiLik0 /tmp/RtmptslIwA/nlmixr2est.Rcheck/00_pkg_src/nlmixr2est/src/inner.cpp:1974
    #10 0x7f21eea9ce16 in foceiOfv0 /tmp/RtmptslIwA/nlmixr2est.Rcheck/00_pkg_src/nlmixr2est/src/inner.cpp:2006
    #11 0x7f21eeae67e7 in foceiOuterFinal(double*, Rcpp::Environment_Impl<Rcpp::PreserveStorage>) /tmp/RtmptslIwA/nlmixr2est.Rcheck/00_pkg_src/nlmixr2est/src/inner.cpp:3515
    #12 0x7f21eeaf5e9d in foceiOuter(Rcpp::Environment_Impl<Rcpp::PreserveStorage>) /tmp/RtmptslIwA/nlmixr2est.Rcheck/00_pkg_src/nlmixr2est/src/inner.cpp:3930
    #13 0x7f21eeb94558 in foceiFitCpp_(Rcpp::Environment_Impl<Rcpp::PreserveStorage>) /tmp/RtmptslIwA/nlmixr2est.Rcheck/00_pkg_src/nlmixr2est/src/inner.cpp:6112
    #14 0x7f21ef2569e7 in _nlmixr2est_foceiFitCpp_ /tmp/RtmptslIwA/nlmixr2est.Rcheck/00_pkg_src/nlmixr2est/src/RcppExports.cpp:293
    #15 0x7f2214eaa166 in R_doDotCall /tmp/r-source/src/main/dotcode.c:601
```

**Comment by mattfidler** [comment]
https://github.com/nlmixr2/nlmixr2est/blob/6ac6a326be567257660972eff3c5d1e6142e5f23/src/inner.cpp#L1273
