### ISSUE TITLE
Model with `est = "rxSolve"` crashes R; with `est = "focei"` works fine

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/nlmixr2est#431]
I have a model where I have fit a subset of the data (including a subset of the IDs), and when I do:

`nlmixr2(object = prior_fit, data = full_data, est = "rxSolve")`

It will crash the R session.

When I do:

`nlmixr2(object = prior_fit, data = full_data, est = "focei")`

it will estimate the model.

Any hints that you may be able to give to understand why it crashes in one case and works in the other?

**Comment by mattfidler** [comment]
Sorry.  No clue from me..

**Comment by mattfidler** [comment]
You could try to get a backtrack with gdb or valgrind I suppose.

**Comment by billdenney** [comment]
Here's the gdb backtrace:

(for my future reference:
```
 R -d gdb
r
[run  the code with a SIGSEGV]
bt
```
)

```
#0  0x00007ffff7ce4e5d in SET_STRING_ELT () from /usr/lib/R/lib/libR.so
#1  0x00007ffff2700669 in Rcpp::internal::string_proxy<16, Rcpp::PreserveStorage>::set (x=<optimized out>, this=<optimized out>)
    at /home/bill/R/x86_64-pc-linux-gnu-library/4.3/Rcpp/include/Rcpp/storage/PreserveStorage.h:75
#2  Rcpp::internal::string_proxy<16, Rcpp::PreserveStorage>::operator= (other=..., other=..., this=<optimized out>)
    at /home/bill/R/x86_64-pc-linux-gnu-library/4.3/Rcpp/include/Rcpp/vector/string_proxy.h:58
#3  etSort (curEt=...) at et.cpp:506
#4  0x00007ffff2710d99 in etImportEventTable (inData=..., warnings=<optimized out>) at et.cpp:1491
#5  0x00007ffff272baaf in et_ (input=..., et__=...) at et.cpp:2294
#6  0x00007ffff26e6bbd in _rxode2et_et_ (inputSEXP=0x555558c26020, et__SEXP=<optimized out>) at RcppExports.cpp:46
#7  0x00007ffff7c522ca in ?? () from /usr/lib/R/lib/libR.so
#8  0x00007ffff7c95273 in ?? () from /usr/lib/R/lib/libR.so
#9  0x00007ffff7ca9d00 in Rf_eval () from /usr/lib/R/lib/libR.so
#10 0x00007ffff7cabd86 in ?? () from /usr/lib/R/lib/libR.so
#11 0x00007ffff7cacbb5 in Rf_applyClosure () from /usr/lib/R/lib/libR.so
#12 0x00007ffff7ca9e2c in Rf_eval () from /usr/lib/R/lib/libR.so
#13 0x00007ffff7c397b9 in R_UnwindProtect () from /usr/lib/R/lib/libR.so
#14 0x00007ffff24d4fcf in Rcpp::unwindProtect (callback=0x7ffff24d40a0 <Rcpp::internal::Rcpp_protected_eval(void*)>, data=0x7ffffffd5c60)
    at /home/bill/R/x86_64-pc-linux-gnu-library/4.3/Rcpp/include/Rcpp/unwindProtect.h:74
#15 0x00007ffff25f74a6 in Rcpp::Rcpp_fast_eval (env=0x5555555a8888, expr=0x55555f388ac8)
    at /home/bill/R/x86_64-pc-linux-gnu-library/4.3/Rcpp/include/Rcpp/api/meat/Rcpp_eval.h:63
#16 Rcpp::Function_Impl<Rcpp::PreserveStorage>::invoke (env=<optimized out>, args_=<optimized out>, this=<optimized out>)
    at /home/bill/R/x86_64-pc-linux-gnu-library/4.3/Rcpp/include/Rcpp/Function.h:118
#17 Rcpp::Function_Impl<Rcpp::PreserveStorage>::operator()<SEXPREC*, SEXPREC*> (t2=<synthetic pointer>: <optimized out>,
    t2=<synthetic pointer>: <optimized out>, t1=<synthetic pointer>: <optimized out>, this=0x7ffffffd5c50)
    at /home/bill/R/x86_64-pc-linux-gnu-library/4.3/Rcpp/include/Rcpp/generated/Function__operator.h:40
#18 _rxode2_et_ (x1=<optimized out>, x2=<optimized out>) at utilcpp.cpp:66
#19 0x00007ffff25839fb in et_ (input=..., et__=...) at /home/bill/R/x86_64-pc-linux-gnu-library/4.3/Rcpp/include/Rcpp/storage/PreserveStorage.h:75
#20 0x00007ffff258da42 in getEtRxsolve (e=...) at rxData.cpp:2252
#21 0x00007ffff25a8efe in updateSolveEnvPost (e=...) at rxData.cpp:2473
#22 0x00007ffff25ab303 in rxSolveGet_rxSolve (obj=..., sarg="ui", exact=..., lst=...) at rxData.cpp:5570
#23 0x00007ffff25ad79c in rxSolveGet (obj=..., arg=..., exact=...) at rxData.cpp:5783
#24 0x00007ffff24ce8f6 in _rxode2_rxSolveGet_try (objSEXP=0x55555cbf8640, argSEXP=<optimized out>, exactSEXP=<optimized out>) at RcppExports.cpp:859
#25 0x00007ffff24cea1b in _rxode2_rxSolveGet (objSEXP=0x55555cbf8640, argSEXP=0x55555c8d3c38, exactSEXP=0x55555c5d76a0) at RcppExports.cpp:867
#26 0x00007ffff7c522ae in ?? () from /usr/lib/R/lib/libR.so
#27 0x00007ffff7c95273 in ?? () from /usr/lib/R/lib/libR.so
#28 0x00007ffff7ca9d00 in Rf_eval () from /usr/lib/R/lib/libR.so
#29 0x00007ffff7cabd86 in ?? () from /usr/lib/R/lib/libR.so
#30 0x00007ffff7cacbb5 in Rf_applyClosure () from /usr/lib/R/lib/libR.so
#31 0x00007ffff7cf22c1 in ?? () from /usr/lib/R/lib/libR.so
#32 0x00007ffff7cf2721 in ?? () from /usr/lib/R/lib/libR.so
#33 0x00007ffff7c8794a in ?? () from /usr/lib/R/lib/libR.so
#34 0x00007ffff7c8d2d5 in ?? () from /usr/lib/R/lib/libR.so
#35 0x00007ffff7ca9d00 in Rf_eval () from /usr/lib/R/lib/libR.so
#36 0x00007ffff7caa6a4 in ?? () from /usr/lib/R/lib/libR.so
#37 0x00007ffff7caa988 in ?? () from /usr/lib/R/lib/libR.so
#38 0x00007ffff7c95d42 in ?? () from /usr/lib/R/lib/libR.so
#39 0x00007ffff7ca9d00 in Rf_eval () from /usr/lib/R/lib/libR.so
#40 0x00007ffff7caa6a4 in ?? () from /usr/lib/R/lib/libR.so
#41 0x00007ffff7caa988 in ?? () from /usr/lib/R/lib/libR.so
#42 0x00007ffff7c95d42 in ?? () from /usr/lib/R/lib/libR.so
#43 0x00007ffff7ca9d00 in Rf_eval () from /usr/lib/R/lib/libR.so
#44 0x00007ffff7caa6a4 in ?? () from /usr/lib/R/lib/libR.so
#45 0x00007ffff7caa988 in ?? () from /usr/lib/R/lib/libR.so
#46 0x00007ffff7c95d42 in ?? () from /usr/lib/R/lib/libR.so
#47 0x00007ffff7ca9d00 in Rf_eval () from /usr/lib/R/lib/libR.so
--Type <RET> for more, q to quit, c to continue without paging--c
#48 0x00007ffff7caa6a4 in ?? () from /usr/lib/R/lib/libR.so
#49 0x00007ffff7caa988 in ?? () from /usr/lib/R/lib/libR.so
#50 0x00007ffff7c95d42 in ?? () from /usr/lib/R/lib/libR.so
#51 0x00007ffff7ca9d00 in Rf_eval () from /usr/lib/R/lib/libR.so
#52 0x00007ffff7caa6a4 in ?? () from /usr/lib/R/lib/libR.so
#53 0x00007ffff7caa988 in ?? () from /usr/lib/R/lib/libR.so
#54 0x00007ffff7c95d42 in ?? () from /usr/lib/R/lib/libR.so
#55 0x00007ffff7ca9d00 in Rf_eval () from /usr/lib/R/lib/libR.so
#56 0x00007ffff7cabd86 in ?? () from /usr/lib/R/lib/libR.so
#57 0x00007ffff7cacbb5 in Rf_applyClosure () from /usr/lib/R/lib/libR.so
#58 0x00007ffff7c9acfd in ?? () from /usr/lib/R/lib/libR.so
#59 0x00007ffff7ca9d00 in Rf_eval () from /usr/lib/R/lib/libR.so
#60 0x00007ffff7cabd86 in ?? () from /usr/lib/R/lib/libR.so
#61 0x00007ffff7cacbb5 in Rf_applyClosure () from /usr/lib/R/lib/libR.so
#62 0x00007ffff7c9acfd in ?? () from /usr/lib/R/lib/libR.so
#63 0x00007ffff7ca9d00 in Rf_eval () from /usr/lib/R/lib/libR.so
#64 0x00007ffff7cabd86 in ?? () from /usr/lib/R/lib/libR.so
#65 0x00007ffff7cacbb5 in Rf_applyClosure () from /usr/lib/R/lib/libR.so
#66 0x00007ffff7c9acfd in ?? () from /usr/lib/R/lib/libR.so
#67 0x00007ffff7ca9d00 in Rf_eval () from /usr/lib/R/lib/libR.so
#68 0x00007ffff7cabd86 in ?? () from /usr/lib/R/lib/libR.so
#69 0x00007ffff7cacbb5 in Rf_applyClosure () from /usr/lib/R/lib/libR.so
#70 0x00007ffff7c9acfd in ?? () from /usr/lib/R/lib/libR.so
#71 0x00007ffff7ca9d00 in Rf_eval () from /usr/lib/R/lib/libR.so
#72 0x00007ffff7cabd86 in ?? () from /usr/lib/R/lib/libR.so
#73 0x00007ffff7cacbb5 in Rf_applyClosure () from /usr/lib/R/lib/libR.so
#74 0x00007ffff7c9acfd in ?? () from /usr/lib/R/lib/libR.so
#75 0x00007ffff7ca9d00 in Rf_eval () from /usr/lib/R/lib/libR.so
#76 0x00007ffff7cabd86 in ?? () from /usr/lib/R/lib/libR.so
#77 0x00007ffff7cacbb5 in Rf_applyClosure () from /usr/lib/R/lib/libR.so
#78 0x00007ffff7c9acfd in ?? () from /usr/lib/R/lib/libR.so
#79 0x00007ffff7ca9d00 in Rf_eval () from /usr/lib/R/lib/libR.so
#80 0x00007ffff7cabd86 in ?? () from /usr/lib/R/lib/libR.so
#81 0x00007ffff7cacbb5 in Rf_applyClosure () from /usr/lib/R/lib/libR.so
#82 0x00007ffff7c9acfd in ?? () from /usr/lib/R/lib/libR.so
#83 0x00007ffff7ca9d00 in Rf_eval () from /usr/lib/R/lib/libR.so
#84 0x00007ffff7cabd86 in ?? () from /usr/lib/R/lib/libR.so
#85 0x00007ffff7cacbb5 in Rf_applyClosure () from /usr/lib/R/lib/libR.so
#86 0x00007ffff7cf22c1 in ?? () from /usr/lib/R/lib/libR.so
#87 0x00007ffff7cf2721 in ?? () from /usr/lib/R/lib/libR.so
#88 0x00007ffff7cf2aa2 in ?? () from /usr/lib/R/lib/libR.so
#89 0x00007ffff7c8f068 in ?? () from /usr/lib/R/lib/libR.so
#90 0x00007ffff7ca9d00 in Rf_eval () from /usr/lib/R/lib/libR.so
#91 0x00007ffff7cabd86 in ?? () from /usr/lib/R/lib/libR.so
#92 0x00007ffff7cacbb5 in Rf_applyClosure () from /usr/lib/R/lib/libR.so
#93 0x00007ffff7ca9e2c in Rf_eval () from /usr/lib/R/lib/libR.so
#94 0x00007ffff7cae892 in ?? () from /usr/lib/R/lib/libR.so
#95 0x00007ffff7caa100 in Rf_eval () from /usr/lib/R/lib/libR.so
#96 0x00007ffff7cdfd0a in Rf_ReplIteration () from /usr/lib/R/lib/libR.so
#97 0x00007ffff7ce00a0 in ?? () from /usr/lib/R/lib/libR.so
#98 0x00007ffff7ce0160 in run_Rmainloop () from /usr/lib/R/lib/libR.so
#99 0x000055555555509f in main ()
#100 0x00007ffff7957d90 in __libc_start_call_main (main=main@entry=0x555555555080 <main>, argc=argc@entry=3, argv=argv@entry=0x7fffffffe3b8) at ../sysdeps/nptl/libc_start_call_main.h:58
#101 0x00007ffff7957e40 in __libc_start_main_impl (main=0x555555555080 <main>, argc=3, argv=0x7fffffffe3b8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffe3a8) at ../csu/libc-start.c:392
#102 0x00005555555550d5 in _start ()
```

**Comment by billdenney** [comment]
The versions used are:

*  nlmixr2_2.1.1
* rxode2parse_2.0.18.9000
* symengine_0.2.2
* rxode2et_2.0.12
* rxode2_2.1.2
