### ISSUE TITLE
SIGSEGV during testing

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/nlmixr2est#89]
This is with current rxode2/nlmixr2est on Linux.

```
> devtools::test()
[Detaching after vfork from child process 2814032]
ℹ Loading nlmixr2est
Loading required package: nlmixr2data
ℹ Testing nlmixr2est
[Detaching after vfork from child process 2814034]
[Detaching after vfork from child process 2814036]
✔ | F W S  OK | Context
⠏ |         0 | broom                                                                                                                               [Detaching after vfork from child process 2814038]
[Detaching after fork from child process 2814040]

Thread 1 "R" received signal SIGSEGV, Segmentation fault.
0x00007fffedb7b610 in user_function (_phi=..., _evt=..., _opt=...)
    at /home/bill/R/x86_64-pc-linux-gnu-library/4.1/RcppArmadillo/include/armadillo_bits/debug.hpp:502
502     arma_check_bounds(const bool state, const T1& x)
(gdb) bt
#0  0x00007fffedb7b610 in user_function (_phi=..., _evt=..., _opt=...)
    at /home/bill/R/x86_64-pc-linux-gnu-library/4.1/RcppArmadillo/include/armadillo_bits/debug.hpp:502
#1  0x00007fffedba9ba3 in SAEM::saem_fit (this=this@entry=0x7ffffff72fe0) at saem.cpp:753
#2  0x00007fffedb7e50a in saem_fit (xSEXP=<optimized out>) at saem.cpp:2147
#3  0x00007fffedc7b8bf in _nlmixr2est_saem_fit (xSEXPSEXP=0x555567fe0fa0)
    at /home/bill/R/x86_64-pc-linux-gnu-library/4.1/Rcpp/include/Rcpp/as.h:164
#4  0x00007ffff7bf5530 in ?? () from /usr/lib/R/lib/libR.so
#5  0x00007ffff7bf5a65 in ?? () from /usr/lib/R/lib/libR.so
#6  0x00007ffff7c4c083 in Rf_eval () from /usr/lib/R/lib/libR.so
#7  0x00007ffff7c50ab2 in ?? () from /usr/lib/R/lib/libR.so
#8  0x00007ffff7c4be3b in Rf_eval () from /usr/lib/R/lib/libR.so
#9  0x00007ffff7c4f4f3 in ?? () from /usr/lib/R/lib/libR.so
#10 0x00007ffff7c4be3b in Rf_eval () from /usr/lib/R/lib/libR.so
#11 0x00007ffff7c4be3b in Rf_eval () from /usr/lib/R/lib/libR.so
#12 0x00007ffff7c4f4f3 in ?? () from /usr/lib/R/lib/libR.so
#13 0x00007ffff7c4be3b in Rf_eval () from /usr/lib/R/lib/libR.so
#14 0x00007ffff7c4d80f in ?? () from /usr/lib/R/lib/libR.so
#15 0x00007ffff7c4e702 in Rf_applyClosure () from /usr/lib/R/lib/libR.so
#16 0x00007ffff7c4bb6f in Rf_eval () from /usr/lib/R/lib/libR.so
#17 0x00007ffff7c4f4f3 in ?? () from /usr/lib/R/lib/libR.so
#18 0x00007ffff7c4be3b in Rf_eval () from /usr/lib/R/lib/libR.so
#19 0x00007ffff7c4c3dc in ?? () from /usr/lib/R/lib/libR.so
#20 0x00007ffff7c4bc5f in Rf_eval () from /usr/lib/R/lib/libR.so
#21 0x00007ffff7c4c3dc in ?? () from /usr/lib/R/lib/libR.so
#22 0x00007ffff7c4c888 in ?? () from /usr/lib/R/lib/libR.so
#23 0x00007ffff7c3725c in ?? () from /usr/lib/R/lib/libR.so
#24 0x00007ffff7c4b948 in Rf_eval () from /usr/lib/R/lib/libR.so
#25 0x00007ffff7c4d80f in ?? () from /usr/lib/R/lib/libR.so
#26 0x00007ffff7c4e702 in Rf_applyClosure () from /usr/lib/R/lib/libR.so
#27 0x00007ffff7c4bb6f in Rf_eval () from /usr/lib/R/lib/libR.so
#28 0x00007ffff7c4f4f3 in ?? () from /usr/lib/R/lib/libR.so
#29 0x00007ffff7c4be3b in Rf_eval () from /usr/lib/R/lib/libR.so
#30 0x00007ffff7c4d80f in ?? () from /usr/lib/R/lib/libR.so
#31 0x00007ffff7c4e702 in Rf_applyClosure () from /usr/lib/R/lib/libR.so
#32 0x00007ffff7c4bb6f in Rf_eval () from /usr/lib/R/lib/libR.so
#33 0x00007ffff7c4f4f3 in ?? () from /usr/lib/R/lib/libR.so
#34 0x00007ffff7c4be3b in Rf_eval () from /usr/lib/R/lib/libR.so
#35 0x00007ffff7c4d80f in ?? () from /usr/lib/R/lib/libR.so
#36 0x00007ffff7c4e702 in Rf_applyClosure () from /usr/lib/R/lib/libR.so
#37 0x00007ffff7c4bb6f in Rf_eval () from /usr/lib/R/lib/libR.so
#38 0x00007ffff7c4fab3 in ?? () from /usr/lib/R/lib/libR.so
#39 0x00007ffff7c4be3b in Rf_eval () from /usr/lib/R/lib/libR.so
#40 0x00007ffff7c4f4f3 in ?? () from /usr/lib/R/lib/libR.so
#41 0x00007ffff7c4be3b in Rf_eval () from /usr/lib/R/lib/libR.so
#42 0x00007ffff7c4d80f in ?? () from /usr/lib/R/lib/libR.so
#43 0x00007ffff7c4e702 in Rf_applyClosure () from /usr/lib/R/lib/libR.so
#44 0x00007ffff7c4bb6f in Rf_eval () from /usr/lib/R/lib/libR.so
#45 0x00007ffff7c4f4f3 in ?? () from /usr/lib/R/lib/libR.so
#46 0x00007ffff7c4be3b in Rf_eval () from /usr/lib/R/lib/libR.so
#47 0x00007ffff7c4d80f in ?? () from /usr/lib/R/lib/libR.so
#48 0x00007ffff7c4e702 in Rf_applyClosure () from /usr/lib/R/lib/libR.so
#49 0x00007ffff7c924f4 in ?? () from /usr/lib/R/lib/libR.so
#50 0x00007ffff7c92930 in ?? () from /usr/lib/R/lib/libR.so
#51 0x00007ffff7c92cf7 in ?? () from /usr/lib/R/lib/libR.so
#52 0x00007ffff7c4be3b in Rf_eval () from /usr/lib/R/lib/libR.so
#53 0x00007ffff7c4f4f3 in ?? () from /usr/lib/R/lib/libR.so
#54 0x00007ffff7c4be3b in Rf_eval () from /usr/lib/R/lib/libR.so
#55 0x00007ffff7c4d80f in ?? () from /usr/lib/R/lib/libR.so
#56 0x00007ffff7c4e702 in Rf_applyClosure () from /usr/lib/R/lib/libR.so
#57 0x00007ffff7c4bb6f in Rf_eval () from /usr/lib/R/lib/libR.so
#58 0x00007ffff7c4c3dc in ?? () from /usr/lib/R/lib/libR.so
#59 0x00007ffff7c4bc5f in Rf_eval () from /usr/lib/R/lib/libR.so
#60 0x00007ffff7c4c3dc in ?? () from /usr/lib/R/lib/libR.so
#61 0x00007ffff7c4c888 in ?? () from /usr/lib/R/lib/libR.so
#62 0x00007ffff7c3725c in ?? () from /usr/lib/R/lib/libR.so
#63 0x00007ffff7c4b948 in Rf_eval () from /usr/lib/R/lib/libR.so
#64 0x00007ffff7c4d80f in ?? () from /usr/lib/R/lib/libR.so
#65 0x00007ffff7c4e702 in Rf_applyClosure () from /usr/lib/R/lib/libR.so
#66 0x00007ffff7c4bb6f in Rf_eval () from /usr/lib/R/lib/libR.so
#67 0x00007ffff7c4c3dc in ?? () from /usr/lib/R/lib/libR.so
#68 0x00007ffff7c4c888 in ?? () from /usr/lib/R/lib/libR.so
#69 0x00007ffff7c3725c in ?? () from /usr/lib/R/lib/libR.so
#70 0x00007ffff7c4b948 in Rf_eval () from /usr/lib/R/lib/libR.so
#71 0x00007ffff7c4c3dc in ?? () from /usr/lib/R/lib/libR.so
#72 0x00007ffff7c4c888 in ?? () from /usr/lib/R/lib/libR.so
#73 0x00007ffff7c3725c in ?? () from /usr/lib/R/lib/libR.so
#74 0x00007ffff7c4b948 in Rf_eval () from /usr/lib/R/lib/libR.so
--Type <RET> for more, q to quit, c to continue without paging--c
#75 0x00007ffff7c4d80f in ?? () from /usr/lib/R/lib/libR.so
#76 0x00007ffff7c4e702 in Rf_applyClosure () from /usr/lib/R/lib/libR.so
#77 0x00007ffff7c39296 in ?? () from /usr/lib/R/lib/libR.so
#78 0x00007ffff7c4b948 in Rf_eval () from /usr/lib/R/lib/libR.so
#79 0x00007ffff7c4d80f in ?? () from /usr/lib/R/lib/libR.so
#80 0x00007ffff7c4e702 in Rf_applyClosure () from /usr/lib/R/lib/libR.so
#81 0x00007ffff7c4bb6f in Rf_eval () from /usr/lib/R/lib/libR.so
#82 0x00007ffff7c50ab2 in ?? () from /usr/lib/R/lib/libR.so
#83 0x00007ffff7c4be3b in Rf_eval () from /usr/lib/R/lib/libR.so
#84 0x00007ffff7c4f4f3 in ?? () from /usr/lib/R/lib/libR.so
#85 0x00007ffff7c4be3b in Rf_eval () from /usr/lib/R/lib/libR.so
#86 0x00007ffff7c4be3b in Rf_eval () from /usr/lib/R/lib/libR.so
#87 0x00007ffff7c4f4f3 in ?? () from /usr/lib/R/lib/libR.so
#88 0x00007ffff7c4be3b in Rf_eval () from /usr/lib/R/lib/libR.so
#89 0x00007ffff7c4d80f in ?? () from /usr/lib/R/lib/libR.so
#90 0x00007ffff7c4e702 in Rf_applyClosure () from /usr/lib/R/lib/libR.so
#91 0x00007ffff7c4bb6f in Rf_eval () from /usr/lib/R/lib/libR.so
#92 0x00007ffff7c4c3dc in ?? () from /usr/lib/R/lib/libR.so
#93 0x00007ffff7c4c888 in ?? () from /usr/lib/R/lib/libR.so
#94 0x00007ffff7c3725c in ?? () from /usr/lib/R/lib/libR.so
#95 0x00007ffff7c4b948 in Rf_eval () from /usr/lib/R/lib/libR.so
#96 0x00007ffff7c4c3dc in ?? () from /usr/lib/R/lib/libR.so
#97 0x00007ffff7c4c888 in ?? () from /usr/lib/R/lib/libR.so
#98 0x00007ffff7c3725c in ?? () from /usr/lib/R/lib/libR.so
#99 0x00007ffff7c4b948 in Rf_eval () from /usr/lib/R/lib/libR.so
#100 0x00007ffff7c4c3dc in ?? () from /usr/lib/R/lib/libR.so
#101 0x00007ffff7c4c888 in ?? () from /usr/lib/R/lib/libR.so
#102 0x00007ffff7c3725c in ?? () from /usr/lib/R/lib/libR.so
#103 0x00007ffff7c4b948 in Rf_eval () from /usr/lib/R/lib/libR.so
#104 0x00007ffff7c4c3dc in ?? () from /usr/lib/R/lib/libR.so
#105 0x00007ffff7c4c888 in ?? () from /usr/lib/R/lib/libR.so
#106 0x00007ffff7c3725c in ?? () from /usr/lib/R/lib/libR.so
#107 0x00007ffff7c4b948 in Rf_eval () from /usr/lib/R/lib/libR.so
#108 0x00007ffff7c4c3dc in ?? () from /usr/lib/R/lib/libR.so
#109 0x00007ffff7c4c888 in ?? () from /usr/lib/R/lib/libR.so
#110 0x00007ffff7c3725c in ?? () from /usr/lib/R/lib/libR.so
#111 0x00007ffff7c4b948 in Rf_eval () from /usr/lib/R/lib/libR.so
#112 0x00007ffff7c4d80f in ?? () from /usr/lib/R/lib/libR.so
#113 0x00007ffff7c4e702 in Rf_applyClosure () from /usr/lib/R/lib/libR.so
#114 0x00007ffff7c39296 in ?? () from /usr/lib/R/lib/libR.so
#115 0x00007ffff7c4b948 in Rf_eval () from /usr/lib/R/lib/libR.so
#116 0x00007ffff7c4d80f in ?? () from /usr/lib/R/lib/libR.so
#117 0x00007ffff7c4e702 in Rf_applyClosure () from /usr/lib/R/lib/libR.so
#118 0x00007ffff7c39296 in ?? () from /usr/lib/R/lib/libR.so
#119 0x00007ffff7c4b948 in Rf_eval () from /usr/lib/R/lib/libR.so
#120 0x00007ffff7c4d80f in ?? () from /usr/lib/R/lib/libR.so
#121 0x00007ffff7c4e702 in Rf_applyClosure () from /usr/lib/R/lib/libR.so
#122 0x00007ffff7c39296 in ?? () from /usr/lib/R/lib/libR.so
#123 0x00007ffff7c4b948 in Rf_eval () from /usr/lib/R/lib/libR.so
#124 0x00007ffff7c4d80f in ?? () from /usr/lib/R/lib/libR.so
#125 0x00007ffff7c4e702 in Rf_applyClosure () from /usr/lib/R/lib/libR.so
#126 0x00007ffff7c39296 in ?? () from /usr/lib/R/lib/libR.so
#127 0x00007ffff7c4b948 in Rf_eval () from /usr/lib/R/lib/libR.so
#128 0x00007ffff7c4d80f in ?? () from /usr/lib/R/lib/libR.so
#129 0x00007ffff7c4e702 in Rf_applyClosure () from /usr/lib/R/lib/libR.so
#130 0x00007ffff7c4bb6f in Rf_eval () from /usr/lib/R/lib/libR.so
#131 0x00007ffff7c4fab3 in ?? () from /usr/lib/R/lib/libR.so
#132 0x00007ffff7c4be3b in Rf_eval () from /usr/lib/R/lib/libR.so
#133 0x00007ffff7c4f4f3 in ?? () from /usr/lib/R/lib/libR.so
#134 0x00007ffff7c4be3b in Rf_eval () from /usr/lib/R/lib/libR.so
#135 0x00007ffff7c54929 in ?? () from /usr/lib/R/lib/libR.so
#136 0x00007ffff7c4be3b in Rf_eval () from /usr/lib/R/lib/libR.so
#137 0x00007ffff7c4f4f3 in ?? () from /usr/lib/R/lib/libR.so
#138 0x00007ffff7c4be3b in Rf_eval () from /usr/lib/R/lib/libR.so
#139 0x00007ffff7c4be3b in Rf_eval () from /usr/lib/R/lib/libR.so
#140 0x00007ffff7c4f4f3 in ?? () from /usr/lib/R/lib/libR.so
#141 0x00007ffff7c4be3b in Rf_eval () from /usr/lib/R/lib/libR.so
#142 0x00007ffff7c4d80f in ?? () from /usr/lib/R/lib/libR.so
#143 0x00007ffff7c4e702 in Rf_applyClosure () from /usr/lib/R/lib/libR.so
#144 0x00007ffff7c4bb6f in Rf_eval () from /usr/lib/R/lib/libR.so
#145 0x00007ffff7c4f4f3 in ?? () from /usr/lib/R/lib/libR.so
#146 0x00007ffff7c4be3b in Rf_eval () from /usr/lib/R/lib/libR.so
#147 0x00007ffff7c4d80f in ?? () from /usr/lib/R/lib/libR.so
#148 0x00007ffff7c4e702 in Rf_applyClosure () from /usr/lib/R/lib/libR.so
#149 0x00007ffff7c924f4 in ?? () from /usr/lib/R/lib/libR.so
#150 0x00007ffff7c92930 in ?? () from /usr/lib/R/lib/libR.so
#151 0x00007ffff7c92cf7 in ?? () from /usr/lib/R/lib/libR.so
#152 0x00007ffff7c4be3b in Rf_eval () from /usr/lib/R/lib/libR.so
#153 0x00007ffff7c4f4f3 in ?? () from /usr/lib/R/lib/libR.so
#154 0x00007ffff7c4be3b in Rf_eval () from /usr/lib/R/lib/libR.so
#155 0x00007ffff7c4d80f in ?? () from /usr/lib/R/lib/libR.so
#156 0x00007ffff7c4e702 in Rf_applyClosure () from /usr/lib/R/lib/libR.so
#157 0x00007ffff7c4bb6f in Rf_eval () from /usr/lib/R/lib/libR.so
#158 0x00007ffff7c4c3dc in ?? () from /usr/lib/R/lib/libR.so
#159 0x00007ffff7c4c888 in ?? () from /usr/lib/R/lib/libR.so
#160 0x00007ffff7c3725c in ?? () from /usr/lib/R/lib/libR.so
#161 0x00007ffff7c4b948 in Rf_eval () from /usr/lib/R/lib/libR.so
#162 0x00007ffff7c4c3dc in ?? () from /usr/lib/R/lib/libR.so
#163 0x00007ffff7c4c888 in ?? () from /usr/lib/R/lib/libR.so
#164 0x00007ffff7c3725c in ?? () from /usr/lib/R/lib/libR.so
#165 0x00007ffff7c4b948 in Rf_eval () from /usr/lib/R/lib/libR.so
#166 0x00007ffff7c4d80f in ?? () from /usr/lib/R/lib/libR.so
#167 0x00007ffff7c4e702 in Rf_applyClosure () from /usr/lib/R/lib/libR.so
#168 0x00007ffff7c39296 in ?? () from /usr/lib/R/lib/libR.so
#169 0x00007ffff7c4b948 in Rf_eval () from /usr/lib/R/lib/libR.so
#170 0x00007ffff7c4d80f in ?? () from /usr/lib/R/lib/libR.so
#171 0x00007ffff7c4e702 in Rf_applyClosure () from /usr/lib/R/lib/libR.so
#172 0x00007ffff7c4bb6f in Rf_eval () from /usr/lib/R/lib/libR.so
#173 0x00007ffff7c4c3dc in ?? () from /usr/lib/R/lib/libR.so
#174 0x00007ffff7c4c888 in ?? () from /usr/lib/R/lib/libR.so
#175 0x00007ffff7c3725c in ?? () from /usr/lib/R/lib/libR.so
#176 0x00007ffff7c4b948 in Rf_eval () from /usr/lib/R/lib/libR.so
#177 0x00007ffff7c4c3dc in ?? () from /usr/lib/R/lib/libR.so
#178 0x00007ffff7c4c888 in ?? () from /usr/lib/R/lib/libR.so
#179 0x00007ffff7c3725c in ?? () from /usr/lib/R/lib/libR.so
#180 0x00007ffff7c4b948 in Rf_eval () from /usr/lib/R/lib/libR.so
#181 0x00007ffff7c4d80f in ?? () from /usr/lib/R/lib/libR.so
#182 0x00007ffff7c4e702 in Rf_applyClosure () from /usr/lib/R/lib/libR.so
#183 0x00007ffff7c39296 in ?? () from /usr/lib/R/lib/libR.so
#184 0x00007ffff7c4b948 in Rf_eval () from /usr/lib/R/lib/libR.so
#185 0x00007ffff7c4d80f in ?? () from /usr/lib/R/lib/libR.so
#186 0x00007ffff7c4e702 in Rf_applyClosure () from /usr/lib/R/lib/libR.so
#187 0x00007ffff7c4bb6f in Rf_eval () from /usr/lib/R/lib/libR.so
#188 0x00007ffff7c50ab2 in ?? () from /usr/lib/R/lib/libR.so
#189 0x00007ffff7c4be3b in Rf_eval () from /usr/lib/R/lib/libR.so
#190 0x00007ffff7c52056 in ?? () from /usr/lib/R/lib/libR.so
#191 0x00007ffff7c30ba1 in ?? () from /usr/lib/R/lib/libR.so
#192 0x00007ffff7c4b948 in Rf_eval () from /usr/lib/R/lib/libR.so
#193 0x00007ffff7c4d80f in ?? () from /usr/lib/R/lib/libR.so
#194 0x00007ffff7c4e702 in Rf_applyClosure () from /usr/lib/R/lib/libR.so
#195 0x00007ffff7c39296 in ?? () from /usr/lib/R/lib/libR.so
#196 0x00007ffff7c4b948 in Rf_eval () from /usr/lib/R/lib/libR.so
#197 0x00007ffff7c4c3dc in ?? () from /usr/lib/R/lib/libR.so
#198 0x00007ffff7c4c888 in ?? () from /usr/lib/R/lib/libR.so
#199 0x00007ffff7c3725c in ?? () from /usr/lib/R/lib/libR.so
#200 0x00007ffff7c4b948 in Rf_eval () from /usr/lib/R/lib/libR.so
#201 0x00007ffff7c4d80f in ?? () from /usr/lib/R/lib/libR.so
#202 0x00007ffff7c4e702 in Rf_applyClosure () from /usr/lib/R/lib/libR.so
#203 0x00007ffff7c39296 in ?? () from /usr/lib/R/lib/libR.so
#204 0x00007ffff7c4b948 in Rf_eval () from /usr/lib/R/lib/libR.so
#205 0x00007ffff7c4c3dc in ?? () from /usr/lib/R/lib/libR.so
#206 0x00007ffff7c4c888 in ?? () from /usr/lib/R/lib/libR.so
#207 0x00007ffff7c3725c in ?? () from /usr/lib/R/lib/libR.so
#208 0x00007ffff7c4b948 in Rf_eval () from /usr/lib/R/lib/libR.so
#209 0x00007ffff7c4c3dc in ?? () from /usr/lib/R/lib/libR.so
#210 0x00007ffff7c4c888 in ?? () from /usr/lib/R/lib/libR.so
#211 0x00007ffff7c3725c in ?? () from /usr/lib/R/lib/libR.so
#212 0x00007ffff7c4b948 in Rf_eval () from /usr/lib/R/lib/libR.so
#213 0x00007ffff7c4c3dc in ?? () from /usr/lib/R/lib/libR.so
#214 0x00007ffff7c4c888 in ?? () from /usr/lib/R/lib/libR.so
#215 0x00007ffff7c3725c in ?? () from /usr/lib/R/lib/libR.so
#216 0x00007ffff7c4b948 in Rf_eval () from /usr/lib/R/lib/libR.so
#217 0x00007ffff7c4c3dc in ?? () from /usr/lib/R/lib/libR.so
#218 0x00007ffff7c4c888 in ?? () from /usr/lib/R/lib/libR.so
#219 0x00007ffff7c3725c in ?? () from /usr/lib/R/lib/libR.so
#220 0x00007ffff7c4b948 in Rf_eval () from /usr/lib/R/lib/libR.so
#221 0x00007ffff7c4c3dc in ?? () from /usr/lib/R/lib/libR.so
#222 0x00007ffff7c4c888 in ?? () from /usr/lib/R/lib/libR.so
#223 0x00007ffff7c3725c in ?? () from /usr/lib/R/lib/libR.so
#224 0x00007ffff7c4b948 in Rf_eval () from /usr/lib/R/lib/libR.so
#225 0x00007ffff7c4d80f in ?? () from /usr/lib/R/lib/libR.so
#226 0x00007ffff7c4e702 in Rf_applyClosure () from /usr/lib/R/lib/libR.so
#227 0x00007ffff7c39296 in ?? () from /usr/lib/R/lib/libR.so
#228 0x00007ffff7c4b948 in Rf_eval () from /usr/lib/R/lib/libR.so
#229 0x00007ffff7c4d80f in ?? () from /usr/lib/R/lib/libR.so
#230 0x00007ffff7c4e702 in Rf_applyClosure () from /usr/lib/R/lib/libR.so
#231 0x00007ffff7c39296 in ?? () from /usr/lib/R/lib/libR.so
#232 0x00007ffff7c4b948 in Rf_eval () from /usr/lib/R/lib/libR.so
#233 0x00007ffff7c4d80f in ?? () from /usr/lib/R/lib/libR.so
#234 0x00007ffff7c4e702 in Rf_applyClosure () from /usr/lib/R/lib/libR.so
#235 0x00007ffff7c39296 in ?? () from /usr/lib/R/lib/libR.so
#236 0x00007ffff7c4b948 in Rf_eval () from /usr/lib/R/lib/libR.so
#237 0x00007ffff7c4c3dc in ?? () from /usr/lib/R/lib/libR.so
#238 0x00007ffff7c4c888 in ?? () from /usr/lib/R/lib/libR.so
#239 0x00007ffff7c3725c in ?? () from /usr/lib/R/lib/libR.so
#240 0x00007ffff7c4b948 in Rf_eval () from /usr/lib/R/lib/libR.so
#241 0x00007ffff7c4c3dc in ?? () from /usr/lib/R/lib/libR.so
#242 0x00007ffff7c4c888 in ?? () from /usr/lib/R/lib/libR.so
#243 0x00007ffff7c3725c in ?? () from /usr/lib/R/lib/libR.so
#244 0x00007ffff7c4b948 in Rf_eval () from /usr/lib/R/lib/libR.so
#245 0x00007ffff7c4d80f in ?? () from /usr/lib/R/lib/libR.so
#246 0x00007ffff7c4e702 in Rf_applyClosure () from /usr/lib/R/lib/libR.so
#247 0x00007ffff7c39296 in ?? () from /usr/lib/R/lib/libR.so
#248 0x00007ffff7c4b948 in Rf_eval () from /usr/lib/R/lib/libR.so
#249 0x00007ffff7c4d80f in ?? () from /usr/lib/R/lib/libR.so
#250 0x00007ffff7c4e702 in Rf_applyClosure () from /usr/lib/R/lib/libR.so
#251 0x00007ffff7c39296 in ?? () from /usr/lib/R/lib/libR.so
#252 0x00007ffff7c4b948 in Rf_eval () from /usr/lib/R/lib/libR.so
#253 0x00007ffff7c4d80f in ?? () from /usr/lib/R/lib/libR.so
#254 0x00007ffff7c4e702 in Rf_applyClosure () from /usr/lib/R/lib/libR.so
#255 0x00007ffff7c39296 in ?? () from /usr/lib/R/lib/libR.so
#256 0x00007ffff7c4b948 in Rf_eval () from /usr/lib/R/lib/libR.so
#257 0x00007ffff7c4d80f in ?? () from /usr/lib/R/lib/libR.so
#258 0x00007ffff7c4e702 in Rf_applyClosure () from /usr/lib/R/lib/libR.so
#259 0x00007ffff7c39296 in ?? () from /usr/lib/R/lib/libR.so
#260 0x00007ffff7c4b948 in Rf_eval () from /usr/lib/R/lib/libR.so
#261 0x00007ffff7c4d80f in ?? () from /usr/lib/R/lib/libR.so
#262 0x00007ffff7c4e702 in Rf_applyClosure () from /usr/lib/R/lib/libR.so
#263 0x00007ffff7c39296 in ?? () from /usr/lib/R/lib/libR.so
#264 0x00007ffff7c4b948 in Rf_eval () from /usr/lib/R/lib/libR.so
#265 0x00007ffff7c4d80f in ?? () from /usr/lib/R/lib/libR.so
#266 0x00007ffff7c4e702 in Rf_applyClosure () from /usr/lib/R/lib/libR.so
#267 0x00007ffff7c39296 in ?? () from /usr/lib/R/lib/libR.so
#268 0x00007ffff7c4b948 in Rf_eval () from /usr/lib/R/lib/libR.so
#269 0x00007ffff7c4d80f in ?? () from /usr/lib/R/lib/libR.so
#270 0x00007ffff7c4e702 in Rf_applyClosure () from /usr/lib/R/lib/libR.so
#271 0x00007ffff7c51029 in R_forceAndCall () from /usr/lib/R/lib/libR.so
#272 0x00007ffff7b7a277 in ?? () from /usr/lib/R/lib/libR.so
#273 0x00007ffff7c9022f in ?? () from /usr/lib/R/lib/libR.so
#274 0x00007ffff7c30991 in ?? () from /usr/lib/R/lib/libR.so
#275 0x00007ffff7c4b948 in Rf_eval () from /usr/lib/R/lib/libR.so
#276 0x00007ffff7c4d80f in ?? () from /usr/lib/R/lib/libR.so
#277 0x00007ffff7c4e702 in Rf_applyClosure () from /usr/lib/R/lib/libR.so
#278 0x00007ffff7c39296 in ?? () from /usr/lib/R/lib/libR.so
#279 0x00007ffff7c4b948 in Rf_eval () from /usr/lib/R/lib/libR.so
#280 0x00007ffff7c4c3dc in ?? () from /usr/lib/R/lib/libR.so
#281 0x00007ffff7c4c888 in ?? () from /usr/lib/R/lib/libR.so
#282 0x00007ffff7c3725c in ?? () from /usr/lib/R/lib/libR.so
#283 0x00007ffff7c4b948 in Rf_eval () from /usr/lib/R/lib/libR.so
#284 0x00007ffff7c4c3dc in ?? () from /usr/lib/R/lib/libR.so
#285 0x00007ffff7c4c888 in ?? () from /usr/lib/R/lib/libR.so
#286 0x00007ffff7c3725c in ?? () from /usr/lib/R/lib/libR.so
#287 0x00007ffff7c4b948 in Rf_eval () from /usr/lib/R/lib/libR.so
#288 0x00007ffff7c4c3dc in ?? () from /usr/lib/R/lib/libR.so
#289 0x00007ffff7c4c888 in ?? () from /usr/lib/R/lib/libR.so
#290 0x00007ffff7c3725c in ?? () from /usr/lib/R/lib/libR.so
#291 0x00007ffff7c4b948 in Rf_eval () from /usr/lib/R/lib/libR.so
#292 0x00007ffff7c4c3dc in ?? () from /usr/lib/R/lib/libR.so
#293 0x00007ffff7c4c888 in ?? () from /usr/lib/R/lib/libR.so
#294 0x00007ffff7c3725c in ?? () from /usr/lib/R/lib/libR.so
#295 0x00007ffff7c4b948 in Rf_eval () from /usr/lib/R/lib/libR.so
#296 0x00007ffff7c4c3dc in ?? () from /usr/lib/R/lib/libR.so
#297 0x00007ffff7c4c888 in ?? () from /usr/lib/R/lib/libR.so
#298 0x00007ffff7c3725c in ?? () from /usr/lib/R/lib/libR.so
#299 0x00007ffff7c4b948 in Rf_eval () from /usr/lib/R/lib/libR.so
#300 0x00007ffff7c4d80f in ?? () from /usr/lib/R/lib/libR.so
#301 0x00007ffff7c4e702 in Rf_applyClosure () from /usr/lib/R/lib/libR.so
#302 0x00007ffff7c39296 in ?? () from /usr/lib/R/lib/libR.so
#303 0x00007ffff7c4b948 in Rf_eval () from /usr/lib/R/lib/libR.so
#304 0x00007ffff7c4d80f in ?? () from /usr/lib/R/lib/libR.so
#305 0x00007ffff7c4e702 in Rf_applyClosure () from /usr/lib/R/lib/libR.so
#306 0x00007ffff7c39296 in ?? () from /usr/lib/R/lib/libR.so
#307 0x00007ffff7c4b948 in Rf_eval () from /usr/lib/R/lib/libR.so
#308 0x00007ffff7c4d80f in ?? () from /usr/lib/R/lib/libR.so
#309 0x00007ffff7c4e702 in Rf_applyClosure () from /usr/lib/R/lib/libR.so
#310 0x00007ffff7c39296 in ?? () from /usr/lib/R/lib/libR.so
#311 0x00007ffff7c4b948 in Rf_eval () from /usr/lib/R/lib/libR.so
#312 0x00007ffff7c4d80f in ?? () from /usr/lib/R/lib/libR.so
#313 0x00007ffff7c4e702 in Rf_applyClosure () from /usr/lib/R/lib/libR.so
#314 0x00007ffff7c39296 in ?? () from /usr/lib/R/lib/libR.so
#315 0x00007ffff7c4b948 in Rf_eval () from /usr/lib/R/lib/libR.so
#316 0x00007ffff7c4d80f in ?? () from /usr/lib/R/lib/libR.so
#317 0x00007ffff7c4e702 in Rf_applyClosure () from /usr/lib/R/lib/libR.so
#318 0x00007ffff7c39296 in ?? () from /usr/lib/R/lib/libR.so
#319 0x00007ffff7c4b948 in Rf_eval () from /usr/lib/R/lib/libR.so
#320 0x00007ffff7c4d80f in ?? () from /usr/lib/R/lib/libR.so
#321 0x00007ffff7c4e702 in Rf_applyClosure () from /usr/lib/R/lib/libR.so
#322 0x00007ffff7c39296 in ?? () from /usr/lib/R/lib/libR.so
#323 0x00007ffff7c4b948 in Rf_eval () from /usr/lib/R/lib/libR.so
#324 0x00007ffff7c4d80f in ?? () from /usr/lib/R/lib/libR.so
#325 0x00007ffff7c4e702 in Rf_applyClosure () from /usr/lib/R/lib/libR.so
#326 0x00007ffff7c39296 in ?? () from /usr/lib/R/lib/libR.so
#327 0x00007ffff7c4b948 in Rf_eval () from /usr/lib/R/lib/libR.so
#328 0x00007ffff7c4d80f in ?? () from /usr/lib/R/lib/libR.so
#329 0x00007ffff7c4e702 in Rf_applyClosure () from /usr/lib/R/lib/libR.so
#330 0x00007ffff7c39296 in ?? () from /usr/lib/R/lib/libR.so
#331 0x00007ffff7c4b948 in Rf_eval () from /usr/lib/R/lib/libR.so
#332 0x00007ffff7c4d80f in ?? () from /usr/lib/R/lib/libR.so
#333 0x00007ffff7c4e702 in Rf_applyClosure () from /usr/lib/R/lib/libR.so
#334 0x00007ffff7c39296 in ?? () from /usr/lib/R/lib/libR.so
#335 0x00007ffff7c4b948 in Rf_eval () from /usr/lib/R/lib/libR.so
#336 0x00007ffff7c4d80f in ?? () from /usr/lib/R/lib/libR.so
#337 0x00007ffff7c4e702 in Rf_applyClosure () from /usr/lib/R/lib/libR.so
#338 0x00007ffff7c4bb6f in Rf_eval () from /usr/lib/R/lib/libR.so
#339 0x00007ffff7c7fe62 in Rf_ReplIteration () from /usr/lib/R/lib/libR.so
#340 0x00007ffff7c80200 in ?? () from /usr/lib/R/lib/libR.so
#341 0x00007ffff7c802c0 in run_Rmainloop () from /usr/lib/R/lib/libR.so
#342 0x000055555555509f in main ()
#343 0x00007ffff79260b3 in __libc_start_main (main=0x555555555080 <main>, argc=3, argv=0x7fffffffe3a8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffe398) at ../csu/libc-start.c:308
#344 0x00005555555550de in _start ()
(gdb)
```

**Comment by billdenney** [comment]
Nevermind, this is related to not cleaning out the object files first.

**Comment by mattfidler** [comment]
Thanks Bill!
